### ISSUE TITLE
Spam - NoSuchFieldError

### ISSUE THREAD

**Issue by ArcasCZ** [Bammerbom/UltimateCore#23] opened 2017-03-29 21:04 UTC
Using latest SpongeForge for 1.10.2 with latest Forge and latest UC.

Log: https://pastebin.com/utYsRUrc

**Comment by JonathanBrouwer** [comment] 2017-03-30 05:06
Duplicate of https://github.com/Bammerbom/UltimateCore/issues/19
You can download a working build at http://www.mediafire.com/file/2j4ki426o62m2mn/UltimateCore.jar

EDIT: The latest release has a fix

**Closed as completed by JonathanBrouwer** 2017-03-30 05:06 UTC
